# Generated by Django 3.2.2 on 2022-06-19 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'permissions': (('assets_assignment', 'Can assign assets'), ('assets_return', 'Can return assets'), ('assets_transfer', 'Can transfer assets')),
            },
        ),
        migrations.CreateModel(
            name='assets_transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('quotation', 'Quotation'), ('memo', 'Memo'), ('p_order', 'Purchase Order')], max_length=50)),
                ('photo', models.FileField(blank=True, null=True, upload_to='inventory/documents')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('acquired', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('requester_comment', models.TextField(blank=True, null=True)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('procurement_date', models.DateField(blank=True, null=True, verbose_name='Date of latest action at Procurement dept.: ')),
                ('finance_date', models.DateField(blank=True, null=True, verbose_name='Date of latest action at Finance dept.: ')),
                ('procurement_comment', models.TextField(blank=True, null=True, verbose_name='Message from Procurement dept.: ')),
                ('finance_comment', models.TextField(blank=True, null=True, verbose_name='Message from Procurement dept.: ')),
            ],
        ),
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('requester_comment', models.TextField(blank=True, null=True)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fin_approved', 'Approved by finance'), ('fin_rejected', 'Rejected by finance'), ('fin_pending', 'Pending at finance'), ('under_maint', 'Under Repair'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('finance_date', models.DateField(blank=True, null=True, verbose_name='Date of latest action at Finance dept.: ')),
                ('finance_comment', models.TextField(blank=True, null=True, verbose_name='Message from Procurement dept.: ')),
            ],
        ),
        migrations.CreateModel(
            name='StatusOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('request_date', models.DateField()),
                ('is_complete', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.assets')),
                ('procurement_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.procurementrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=50)),
                ('pan_number', models.CharField(max_length=50)),
                ('vendor_documents', models.FileField(blank=True, null=True, upload_to='inventory/vendor_doc')),
            ],
        ),
        migrations.CreateModel(
            name='transaction_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unregistered_item', to='inventory.item')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unregistered_item_type', to='inventory.assets')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unregistered_transaction', to='inventory.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor'),
        ),
    ]
