# Generated by Django 3.2.2 on 2022-06-19 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_management_app', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='statusoptions',
            name='current_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_currentdept', to='student_management_app.branch'),
        ),
        migrations.AddField(
            model_name='statusoptions',
            name='goto_branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status_gotodept', to='student_management_app.branch'),
        ),
        migrations.AddField(
            model_name='repairrequest',
            name='finance_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_personnel_repair', to=settings.AUTH_USER_MODEL, verbose_name='Latest action at Finance dept. by: '),
        ),
        migrations.AddField(
            model_name='repairrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_item', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='repairrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repairrequest',
            name='requester_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_requester_branch', to='student_management_app.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='repairrequest',
            name='requester_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_requester_dept', to='student_management_app.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='finance_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_personnel', to=settings.AUTH_USER_MODEL, verbose_name='Latest action at Finance dept. by: '),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.assets'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='procurement_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procurement_personnel', to=settings.AUTH_USER_MODEL, verbose_name='Latest action at Procurement dept. by: '),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='requester_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requester_branch', to='student_management_app.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='requester_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procurement_dept', to='student_management_app.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='inventory.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='current_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.branch'),
        ),
        migrations.AddField(
            model_name='item',
            name='current_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.department'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_type', to='inventory.assets', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='item',
            name='source_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_transaction', to='inventory.transaction'),
        ),
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.department'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assets_transfer',
            name='from_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_transfer_from_branch', to='student_management_app.branch'),
        ),
        migrations.AddField(
            model_name='assets_transfer',
            name='from_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_transfer_from', to='student_management_app.department'),
        ),
        migrations.AddField(
            model_name='assets_transfer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='assets_transfer',
            name='overseer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assets_transfer',
            name='to_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_transfer_to_branch', to='student_management_app.branch'),
        ),
        migrations.AddField(
            model_name='assets_transfer',
            name='to_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_transfer_to', to='student_management_app.department'),
        ),
        migrations.AddField(
            model_name='assets',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
    ]
