# Generated by Django 3.2.2 on 2023-04-20 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student_management_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_management_app.semester",
                verbose_name="Class",
            ),
        ),
    ]
