# Generated by Django 3.2.2 on 2022-05-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_auto_20220118_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ('pk',), 'verbose_name': 'semester', 'verbose_name_plural': 'semesters'},
        ),
    ]
