# Generated by Django 3.2.2 on 2022-05-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_alter_semester_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsemester',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalsubject',
            name='subject_code',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
