# Generated by Django 3.2.2 on 2023-04-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_management_app", "0003_auto_20230420_1338"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="subject_name",
        ),
        migrations.AddField(
            model_name="subject",
            name="subject_name",
            field=models.ManyToManyField(
                to="student_management_app.SubjectChoices"),
        ),
    ]
