# Generated by Django 3.2.2 on 2022-05-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_auto_20220516_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubject',
            name='subject_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
