# Generated by Django 3.2.2 on 2022-05-18 02:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_auto_20220516_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='staff_user',
            field=models.ManyToManyField(blank=True, through='student_management_app.SubjectTeacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
