# Generated by Django 3.2.2 on 2022-06-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_section_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='session_year',
        ),
    ]
