# Generated by Django 3.2.2 on 2022-06-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_remove_student_session_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='qr_code',
        ),
    ]
