# Generated by Django 3.2.2 on 2022-06-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_auto_20220614_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='bachelor_semester',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='level',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='master_semester',
        ),
    ]
