# Generated by Django 3.2.2 on 2022-06-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_student_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
    ]
