# Generated by Django 3.2.2 on 2022-06-19 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_auto_20220614_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='category',
        ),
    ]
