# Generated by Django 3.2.2 on 2022-06-19 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_remove_section_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.semester', verbose_name='Class'),
        ),
    ]
