# Generated by Django 3.2.2 on 2023-07-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_management_app", "0009_alter_student_roll_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Others", "Others")],
                default="Male",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="shift",
            field=models.CharField(
                blank=True,
                choices=[("Morning", "Morning"), ("Day", "Day")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="stu_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
