# Generated by Django 3.2.2 on 2022-07-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_remove_student_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectteacher',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.semester'),
        ),
    ]
