# Generated by Django 3.2.2 on 2022-06-19 06:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_alter_section_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='bachelor_semester',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='master_semester',
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.semester', verbose_name='Class'),
            preserve_default=False,
        ),
    ]
