# Generated by Django 3.2.2 on 2022-07-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_subjectteacher_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('view_superadmin_home ', 'Can View  Superadmin Home'),), 'verbose_name': 'customuser', 'verbose_name_plural': 'customusers'},
        ),
    ]
