# Generated by Django 3.2.2 on 2023-07-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_alter_student_stu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_id',
            field=models.CharField(max_length=20),
        ),
    ]
