# Generated by Django 3.2.2 on 2022-07-21 12:00

from django.db import migrations, models
import student_management_system.validators


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_auto_20220710_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='contact',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, upload_to='Complain_attachment', validators=[student_management_system.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(max_length=500, upload_to='document_files', validators=[student_management_system.validators.img_pdf_file_validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='extrauser',
            name='contact',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
