# Generated by Django 3.2.2 on 2023-07-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0013_alter_student_stu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
