# Generated by Django 3.2.2 on 2023-07-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_management_app", "0016_auto_20230712_2031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="roll_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
