# Generated by Django 3.2.2 on 2022-07-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0016_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('view_superadmin_home ', 'Can View  Superadmin Home'), ('view_academic_sidebar ', 'Can View  Academic Sidebar'), ('view_permission_sidebar ', 'Can View  Permission Sidebar'), ('view_event_sidebar ', 'Can View  Event Sidebar'), ('view_user_sidebar ', 'Can View  User Sidebar'), ('view_attendance_sidebar ', 'Can View  Attendance Sidebar'), ('view_announcement_sidebar ', 'Can View  Announcement Sidebar')), 'verbose_name': 'customuser', 'verbose_name_plural': 'customusers'},
        ),
    ]
