# Generated by Django 3.2.2 on 2023-07-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0018_rename_stu_id_student_martix_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='martix_id',
            new_name='matrix_id',
        ),
    ]
