# Generated by Django 3.2.2 on 2023-04-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0018_auto_20230409_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='contact',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
