# Generated by Django 3.2.2 on 2022-08-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0018_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseToCourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.coursecategory', verbose_name='Subject')),
            ],
        ),
    ]
