# Generated by Django 3.2.2 on 2023-04-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0019_alter_adminuser_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauser',
            name='contact',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
