# Generated by Django 3.2.2 on 2023-07-12 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student_management_app", "0019_rename_martix_id_student_matrix_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="matrix_id",
            new_name="stu_id",
        ),
    ]
