# Generated by Django 3.2.2 on 2022-08-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0019_coursetocoursecategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseToCourseCategory',
        ),
    ]
