# Generated by Django 3.2.2 on 2023-07-13 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0022_alter_student_stu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='home_phone',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
