# Generated by Django 3.2.2 on 2022-08-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0023_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='semester_choices',
            field=models.CharField(blank=True, choices=[('First Semester ', 'First Semester'), ('Second Semester', 'Second Semester'), ('Third Semester', 'Third Semester'), ('Fourth Semester', 'Fourth Semester'), ('Fifth Semester', 'Fifth Semester'), ('Sixth Semester', 'Sixth Semester'), ('Seventh Semester', 'Seventh Semester'), ('Eight Semester', 'Eight Semester')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='year_choices',
            field=models.CharField(blank=True, choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year'), ('Fifth Year', 'Fifth Year')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='year_semester_check',
            field=models.CharField(blank=True, choices=[('Has Year', 'Has Year'), ('Has Semester', 'Has Semester')], max_length=100, null=True),
        ),
    ]
