# Generated by Django 3.2.2 on 2022-08-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0024_auto_20220809_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year_semester_check',
            field=models.CharField(blank=True, choices=[('Has Year', 'Has Year'), ('Has Semester', 'Has Semester')], max_length=100, null=True, verbose_name='Has Semester/Year'),
        ),
    ]
