# Generated by Django 3.2.2 on 2023-07-16 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("student_management_app", "0024_auto_20230713_1837"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="subject_code",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
