# Generated by Django 3.2.2 on 2022-08-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('student_management_app', '0026_auto_20220810_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='semester_choices',
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_choices',
            field=models.ManyToManyField(blank=True, null=True, to='classroom.SemesterModel'),
        ),
        migrations.RemoveField(
            model_name='semester',
            name='year_choices',
        ),
        migrations.AddField(
            model_name='semester',
            name='year_choices',
            field=models.ManyToManyField(blank=True, null=True, to='classroom.YearModel'),
        ),
    ]
