# Generated by Django 3.2.2 on 2022-08-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0029_alter_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year_semester_check',
            field=models.CharField(blank=True, choices=[('Has Year', 'Has Year'), ('Has Semester', 'Has Semester'), ('No Semester/Year', 'No Semester/Year')], max_length=100, null=True, verbose_name='Has Semester/Year'),
        ),
    ]
