# Generated by Django 3.2.2 on 2023-04-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0030_alter_semester_year_semester_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='passed_year',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2023, verbose_name='Passed Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='join_year',
            field=models.CharField(blank=True, default=2023, max_length=50, null=True, verbose_name='Join Year'),
        ),
    ]
