# Generated by Django 3.2 on 2021-08-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20210805_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='graded_sheet',
            field=models.FileField(blank=True, null=True, upload_to='Student_answers/graded_sheets'),
        ),
    ]
