# Generated by Django 3.2 on 2021-08-05 06:48

from django.db import migrations, models
import school_apps.exam.models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0004_alter_answersheet_graded_sheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answersheet",
            name="answer_upload",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="Student_answers/student_answers"),
        ),
        migrations.AlterField(
            model_name="answersheet",
            name="graded_sheet",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="Student_answers/graded_sheets"),
        ),
    ]
