# Generated by Django 3.2.2 on 2022-06-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalEvent',
        ),
    ]
