# Generated by Django 3.2.2 on 2023-04-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_day', models.CharField(max_length=20, verbose_name='Event Date')),
                ('english_date', models.DateField(blank=True, null=True)),
                ('year', models.SlugField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Holiday', 'Holiday'), ('Event', 'Event')], max_length=20)),
            ],
        ),
    ]
