# Generated by Django 3.2.2 on 2023-04-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='year',
        ),
    ]
