# Generated by Django 3.2.2 on 2022-01-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('route_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_vehicle', models.PositiveIntegerField()),
                ('driver_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'transport',
                'verbose_name_plural': 'transports',
                'db_table': 'tbl_Transport',
            },
        ),
    ]
