# Generated by Django 3.2.2 on 2022-01-14 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(blank=True, max_length=60)),
                ('home_contact', models.CharField(blank=True, max_length=60, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=60, null=True)),
                ('category', models.CharField(choices=[('ACA', 'Academic'), ('NON', 'Non-Academic')], default='ACA', max_length=5, verbose_name='Reason')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Reason for visit')),
                ('recipient', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.department')),
            ],
        ),
    ]
