# Generated by Django 3.2.2 on 2022-06-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnotice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalnotice',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalHoliday',
        ),
        migrations.DeleteModel(
            name='HistoricalNotice',
        ),
    ]
