# Generated by Django 3.2.2 on 2023-04-15 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="application_form",
            fields=[
                (
                    "application_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("status", models.BooleanField(default=True, max_length=3)),
                (
                    "application_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("remarks", models.CharField(default="No Remarks", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Exams",
            fields=[
                (
                    "exam_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("exam_title", models.CharField(max_length=100)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("Unit", "Unit Test"),
                            ("Term", "Terminal Examination"),
                        ],
                        default="Unit",
                        max_length=5,
                    ),
                ),
                (
                    "exam_format",
                    models.CharField(
                        choices=[
                            ("Open Book", "Open Book"),
                            ("Close Book", "Closed Book"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("full_marks", models.IntegerField(default=100)),
                ("pass_marks", models.IntegerField(default=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="selectedcourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (1990, 1990),
                            (1991, 1991),
                            (1992, 1992),
                            (1993, 1993),
                            (1994, 1994),
                            (1995, 1995),
                            (1996, 1996),
                            (1997, 1997),
                            (1998, 1998),
                            (1999, 1999),
                            (2000, 2000),
                            (2001, 2001),
                            (2002, 2002),
                            (2003, 2003),
                            (2004, 2004),
                            (2005, 2005),
                            (2006, 2006),
                            (2007, 2007),
                            (2008, 2008),
                            (2009, 2009),
                            (2010, 2010),
                            (2011, 2011),
                            (2012, 2012),
                            (2013, 2013),
                            (2014, 2014),
                            (2015, 2015),
                            (2016, 2016),
                            (2017, 2017),
                            (2018, 2018),
                            (2019, 2019),
                            (2020, 2020),
                            (2021, 2021),
                            (2022, 2022),
                            (2023, 2023),
                        ],
                        default=2023,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="studentgrades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.FloatField(default=0)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A*", "A*"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("U", "U"),
                            ("Abs", "Absent"),
                        ],
                        default="U",
                        max_length=6,
                    ),
                ),
                ("passed", models.BooleanField()),
                ("exam_type", models.BooleanField()),
                ("is_absent", models.BooleanField(default=False)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "term_id",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (1990, 1990),
                            (1991, 1991),
                            (1992, 1992),
                            (1993, 1993),
                            (1994, 1994),
                            (1995, 1995),
                            (1996, 1996),
                            (1997, 1997),
                            (1998, 1998),
                            (1999, 1999),
                            (2000, 2000),
                            (2001, 2001),
                            (2002, 2002),
                            (2003, 2003),
                            (2004, 2004),
                            (2005, 2005),
                            (2006, 2006),
                            (2007, 2007),
                            (2008, 2008),
                            (2009, 2009),
                            (2010, 2010),
                            (2011, 2011),
                            (2012, 2012),
                            (2013, 2013),
                            (2014, 2014),
                            (2015, 2015),
                            (2016, 2016),
                            (2017, 2017),
                            (2018, 2018),
                            (2019, 2019),
                            (2020, 2020),
                            (2021, 2021),
                            (2022, 2022),
                            (2023, 2023),
                        ],
                        default=2023,
                    ),
                ),
                ("term_name", models.CharField(max_length=25)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Unit", "Unit Test"),
                            ("Term", "Terminal Examination"),
                        ],
                        default="Unit",
                        max_length=5,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("exam_centre", models.CharField(max_length=30)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="term_ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_marks", models.IntegerField(default=0)),
                ("rank", models.IntegerField(default=0)),
            ],
        ),
    ]
