# Generated by Django 3.2.2 on 2023-04-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exams",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exams",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
