# Generated by Django 3.2.2 on 2022-08-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_form',
            name='status',
            field=models.BooleanField(default=False, max_length=3),
        ),
    ]
