# Generated by Django 3.2.2 on 2022-06-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalexams',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalexams',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='historicalexams',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='historicalexams',
            name='term',
        ),
        migrations.RemoveField(
            model_name='historicalselectedcourses',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalselectedcourses',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='historicalselectedcourses',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='historicalselectedcourses',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='historicalstudentgrades',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='historicalstudentgrades',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='historicalstudentgrades',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalterm',
            name='course_category',
        ),
        migrations.RemoveField(
            model_name='historicalterm',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Historicalapplication_form',
        ),
        migrations.DeleteModel(
            name='HistoricalExams',
        ),
        migrations.DeleteModel(
            name='Historicalselectedcourses',
        ),
        migrations.DeleteModel(
            name='Historicalstudentgrades',
        ),
        migrations.DeleteModel(
            name='HistoricalTerm',
        ),
    ]
