# Generated by Django 3.2.2 on 2022-08-10 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_application_form_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='term_ranking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term_ranking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
