# Generated by Django 3.2.2 on 2023-04-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_alter_subject_semester'),
        ('courses', '0008_studentgrades_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrades',
            name='subject',
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.student'),
        ),
    ]
