# Generated by Django 3.2.2 on 2023-04-20 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20230420_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrades',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.term'),
        ),
    ]
