# Generated by Django 3.2.2 on 2023-04-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_studentgrades_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="full_marks",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="term",
            name="pass_marks",
            field=models.IntegerField(default=40),
        ),
    ]
