# Generated by Django 3.2.2 on 2023-04-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20230420_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='full_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='term',
            name='pass_marks',
            field=models.IntegerField(default=40),
        ),
    ]
