# Generated by Django 3.2.2 on 2023-04-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20230420_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrades',
            name='exam_type',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
