# Generated by Django 3.2.2 on 2023-07-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_studentgrades_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='term_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
