# Generated by Django 3.2.2 on 2022-06-19 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_management_app', '0001_initial'),
        ('formapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.department'),
        ),
    ]
