# Generated by Django 3.2.2 on 2023-04-19 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="url_link",
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
