# Generated by Django 3.2.2 on 2022-06-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalroutine',
            name='course',
        ),
        migrations.RemoveField(
            model_name='historicalroutine',
            name='course_category',
        ),
        migrations.RemoveField(
            model_name='historicalroutine',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalroutine',
            name='section',
        ),
        migrations.RemoveField(
            model_name='historicalroutine',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='historicalsyllabus',
            name='course_category',
        ),
        migrations.RemoveField(
            model_name='historicalsyllabus',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsyllabus',
            name='semester',
        ),
        migrations.DeleteModel(
            name='HistoricalAssignment',
        ),
        migrations.DeleteModel(
            name='HistoricalRoutine',
        ),
        migrations.DeleteModel(
            name='HistoricalSyllabus',
        ),
    ]
