# Generated by Django 3.2.2 on 2022-07-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_alter_customuser_options'),
        ('academic', '0003_assignment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='course_category',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.course'),
        ),
    ]
