# Generated by Django 3.2.2 on 2023-04-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_assignment_url_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='url_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
