# Generated by Django 3.2.2 on 2022-07-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_auto_20220706_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enotes',
            options={'verbose_name_plural': 'Syllabus'},
        ),
        migrations.RemoveField(
            model_name='routine',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='updated_at',
        ),
        migrations.AlterModelTable(
            name='assignment',
            table='tbl_Assignment',
        ),
        migrations.AlterModelTable(
            name='enotes',
            table='tbl_Enotes',
        ),
        migrations.AlterModelTable(
            name='routine',
            table='tbl_Routine',
        ),
        migrations.AlterModelTable(
            name='syllabus',
            table='tbl_Syllabus',
        ),
    ]
