# Generated by Django 3.2.2 on 2022-07-06 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_auto_20220706_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
