# Generated by Django 3.2.2 on 2022-07-06 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_alter_customuser_options'),
        ('academic', '0009_auto_20220706_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enotes',
            name='note_category',
            field=models.CharField(blank=True, choices=[('Subject Notes', 'Subject Notes'), ('Extra Notes', 'Extra Notes')], max_length=50),
        ),
    ]
