# Generated by Django 3.2.2 on 2022-07-06 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_alter_customuser_options'),
        ('academic', '0010_auto_20220706_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='enotes',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.section'),
            preserve_default=False,
        ),
    ]
