# Generated by Django 3.2.2 on 2022-07-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_enotes_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enotes',
            name='note_category',
            field=models.CharField(choices=[('Subject Notes', 'Subject Notes'), ('Extra Notes', 'Extra Notes')], max_length=50),
        ),
    ]
