# Generated by Django 3.2.2 on 2022-07-10 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_auto_20220710_1948'),
        ('academic', '0012_alter_enotes_note_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.section'),
        ),
    ]
