# Generated by Django 3.2.2 on 2022-07-21 10:49

from django.db import migrations, models
import student_management_system.validators


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_grade_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='Assignment_section', validators=[student_management_system.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='enotes',
            name='file',
            field=models.FileField(max_length=500, upload_to='e-notes', validators=[student_management_system.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='answer_upload',
            field=models.FileField(max_length=500, null=True, upload_to='Assignment_grades', validators=[student_management_system.validators.img_pdf_file_validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='routine',
            name='routine_file',
            field=models.FileField(max_length=500, upload_to='College Routine', validators=[student_management_system.validators.img_pdf_doc_validator], verbose_name='Routine'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='file',
            field=models.FileField(max_length=500, upload_to='syllabus', validators=[student_management_system.validators.img_pdf_file_validate_file_extension]),
        ),
    ]
