# Generated by Django 3.2.2 on 2022-07-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_alter_syllabus_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='semester',
        ),
    ]
