# Generated by Django 3.2.2 on 2022-07-21 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0014_alter_student_contact'),
        ('academic', '0017_remove_syllabus_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.semester'),
        ),
    ]
