# Generated by Django 3.2.2 on 2022-07-25 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0015_alter_complain_user'),
        ('academic', '0018_syllabus_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enotes',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.section'),
        ),
    ]
