# Generated by Django 3.2.2 on 2022-08-05 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_alter_enotes_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grade_status',
        ),
        migrations.CreateModel(
            name='AssignmentReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_mark', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.CharField(blank=True, default='No feedback', max_length=255, null=True)),
                ('grade_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_return', to='academic.assignment')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.grade')),
            ],
        ),
    ]
