# Generated by Django 3.2.2 on 2022-08-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0020_auto_20220805_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentreturn',
            name='grade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academic.grade'),
        ),
    ]
