# Generated by Django 3.2.2 on 2022-08-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0022_alter_assignmentreturn_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentreturn',
            name='feedback',
            field=models.TextField(blank=True, default='No feedback', max_length=255, null=True),
        ),
    ]
