# Generated by Django 3.2.2 on 2022-08-16 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0023_alter_assignmentreturn_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentreturn',
            name='grade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='academic.grade'),
        ),
    ]
