# Generated by Django 3.2.2 on 2022-06-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='application/student')),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=100)),
                ('temporary_address', models.CharField(max_length=250)),
                ('permanent_address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('home_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_office', models.CharField(blank=True, max_length=100, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_office', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_address', models.CharField(max_length=100)),
                ('guardian_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_office', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('additional_fields', models.JSONField(blank=True, null=True)),
                ('discovery', models.TextField(blank=True, null=True, verbose_name='How did you know about this college?')),
                ('status', models.CharField(blank=True, choices=[('APL', 'Applied'), ('ENT_PASSED', 'Entrance Exam passed'), ('INT_PASSED', 'Interview passed'), ('ENR', 'Enrolled'), ('DRP', 'Dropped')], default='APL', max_length=100)),
                ('entrance_marks', models.IntegerField(blank=True, null=True)),
                ('entrance_result', models.CharField(choices=[('PASS', 'Passed'), ('FAIL', 'Failed'), ('NA', 'Not appeared yet')], default='NA', max_length=10)),
                ('entrance_result_sent', models.BooleanField(default=False)),
                ('interview_result', models.CharField(choices=[('PASS', 'Passed'), ('FAIL', 'Failed'), ('NA', 'Not appeared yet')], default='NA', max_length=10)),
                ('interview_result_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(blank=True, max_length=60)),
                ('home_contact', models.CharField(blank=True, max_length=60)),
                ('mobile_no', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('discovery_method', models.CharField(blank=True, max_length=250, verbose_name='How did you know about this college?')),
                ('called', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('ENQ', 'Enquired'), ('APL_SENT', 'Application Sent'), ('APL', 'Applied'), ('DRP', 'Dropped')], default='ENQ', max_length=100)),
                ('application_sent', models.BooleanField(default=False)),
                ('entrance_marks', models.IntegerField(blank=True, null=True)),
                ('entrance_result', models.CharField(choices=[('PASS', 'Passed'), ('FAIL', 'Failed'), ('NA', 'Not appeared yet')], default='NA', max_length=10)),
                ('entrance_result_sent', models.BooleanField(default=False)),
                ('interview_result', models.CharField(choices=[('PASS', 'Passed'), ('FAIL', 'Failed'), ('NA', 'Not appeared yet')], default='NA', max_length=10)),
                ('interview_result_sent', models.BooleanField(default=False)),
                ('enquiry', models.CharField(blank=True, max_length=250, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
