# Generated by Django 3.2.2 on 2022-03-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='discovery',
            field=models.TextField(blank=True, null=True, verbose_name='How did you know about this college?'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='discovery_method',
            field=models.CharField(blank=True, max_length=250, verbose_name='How did you know about this college?'),
        ),
    ]
